# Generated by Django 5.2.7 on 2025-10-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('funding_needed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('FinTech', 'FinTech'), ('GameDev', 'Game Development'), ('EdTech', 'Education Technology')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
