# Generated by Django 5.2.7 on 2025-10-18 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='category',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('FinTech', 'Financial Technology'), ('GameDev', 'Game Development'), ('EdTech', 'Education Technology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='startup',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startup',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
