# Generated by Django 5.2.7 on 2025-10-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_startup_category_alter_startup_founder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
